version: '3.0'
services:
  db:
    image: mongo
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test

  node:
    image: node
    working_dir: /home/node/app
    volumes:
      - ./manager-server:/home/node/app
    ports:
    - 3000:3000
    command: "node index.js"
